# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webrtc_pusher.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='webrtc_pusher.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13webrtc_pusher.proto\" \n\x03SDP\x12\x0b\n\x03sdp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t2*\n\rWebRTC_Pusher\x12\x19\n\tNegotiate\x12\x04.SDP\x1a\x04.SDP\"\x00\x62\x06proto3'
)




_SDP = _descriptor.Descriptor(
  name='SDP',
  full_name='SDP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdp', full_name='SDP.sdp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='SDP.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['SDP'] = _SDP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SDP = _reflection.GeneratedProtocolMessageType('SDP', (_message.Message,), {
  'DESCRIPTOR' : _SDP,
  '__module__' : 'webrtc_pusher_pb2'
  # @@protoc_insertion_point(class_scope:SDP)
  })
_sym_db.RegisterMessage(SDP)



_WEBRTC_PUSHER = _descriptor.ServiceDescriptor(
  name='WebRTC_Pusher',
  full_name='WebRTC_Pusher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=57,
  serialized_end=99,
  methods=[
  _descriptor.MethodDescriptor(
    name='Negotiate',
    full_name='WebRTC_Pusher.Negotiate',
    index=0,
    containing_service=None,
    input_type=_SDP,
    output_type=_SDP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBRTC_PUSHER)

DESCRIPTOR.services_by_name['WebRTC_Pusher'] = _WEBRTC_PUSHER

# @@protoc_insertion_point(module_scope)
